name: "MR Pipeline"

on:
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/ci.yml"
      - "poetry.lock"
      - "pyproject.toml"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run ruff linter
        run: poetry run ruff check
      - name: Run ruff formatter
        run: poetry run ruff format --check
  type:
    name: "Type-Check"
    runs-on: ubuntu-latest
    needs:
      - lint
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run mypy
        run: poetry run mypy
  tests:
    name: Unit-Tests
    runs-on: ubuntu-latest
    needs:
      - type
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          cache: "poetry"
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run pytest
        run: poetry run pytest
